image: docker:git

stages:
  - build-container
  - deploy

services:
  - docker:dind

# variables:
#   DOCKER_HOST: tcp://localhost:2375/

initial:
  stage: build-container
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - >-
      docker build -t registry.gitlab.com/maiot/frontend/ci:latest
      -f .ci/Dockerfile .
    - docker push registry.gitlab.com/maiot/frontend/ci:latest
  only:
    changes:
      - .ci/Dockerfile
      - package.json
      - .ci/force-builds

production:
  stage: deploy
  variables:
    AWS_BUCKET: app.zenml.io
    REACT_APP_BASE_API_URL: https://api.zenml.io/api/v1
    REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_live_51HHtJnCvKKdV9NkDX6raJvgd1gGxNHiPir1Zny3c7Y2M24HpG3MatuRNgZpAEFxuxibmhgtDdnyaETDpySYcwHA7002wYvNMHK
    CLOUDFRONT_DISTRIBUTION: E3U43JWH3PYEHB
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - >-
      docker run 
      -v $(pwd):/ci 
      -w /ci 
      -e REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}
      -e REACT_APP_STRIPE_PUBLISHABLE_KEY=${REACT_APP_STRIPE_PUBLISHABLE_KEY}
      registry.gitlab.com/maiot/frontend/ci:latest 
      /bin/bash -c "mv /dependencies/* ./ && yarn build"
    - >-
      docker run 
      -v $(pwd):/ci 
      -w /ci 
      -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
      -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      mesosphere/aws-cli:1.14.5 
      s3 sync ./build/ s3://${AWS_BUCKET} --region eu-central-1 --delete
    - >-
      docker run 
      -v $(pwd):/ci 
      -w /ci 
      -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
      -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      mesosphere/aws-cli:1.14.5 
      s3api put-bucket-website --bucket ${AWS_BUCKET} --website-configuration=file://website-config.json
    - >-
      docker run 
      -v $(pwd):/ci 
      -w /ci 
      -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
      -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} 
      mesosphere/aws-cli:1.14.5 
      cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths "/*"
  environment:
    name: production
    url: https://app.zenml.io
  only:
    - master
