name: Release-pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.20.0
      - name: Install yarn
        run: npm install --global yarn
      - name: Build
        run: |
          yarn install
          yarn build
        env:
          REACT_APP_BASE_API_URL: "/api/v1"
          REACT_APP_MOCKAPI_RESPONSE: false
          REACT_APP_VERSION: ${{ github.ref }}
      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: "false"
          onlyLastTag: "true"
          stripGeneratorNotice: "true"
          issuesWoLabels: "true"
          stripHeaders: "true"
      - name: Create release archive
        run: |
          tar -zcf zenml-dashboard.tar.gz -C build --transform="s#\.\/##" .
          sha256sum -b zenml-dashboard.tar.gz > zenml-dashboard.tar.gz.sha256
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            zenml-dashboard.tar.gz
            zenml-dashboard.tar.gz.sha256
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
